import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

import dynamic from 'next/dynamic'
import Loading from '@/ui/Loading'

const Navbar = dynamic(() => import('@/components/navbar/navbar'))
const Footer = dynamic(() => import('@/components/footer/footer'))
const Providers = dynamic(() => import('@/app/providers'), {
	loading: () => <Loading />
})

const inter = Be_Vietnam_Pro({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Youcode - Online Education',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html
			lang='en'
			className='bg-gray-100'
		>
			<body className={`${inter.className} `}>
				<Providers>
					<Navbar />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
